# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: scottymerks
email: scottmerker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pretty much just an awesome display of awesomeness.  And some more awesome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scottymerks.com" # the base hostname & protocol for your site
twitter_username: scottymerks
github_username:  scottmerker

# Build settings
markdown: kramdown
